"""
Configuration modules for Sentinel-2 processing
"""

from .ingestion_config import (
    BASE_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR,
    BAND_RESOLUTIONS, RGB_BANDS, QUALITY_BANDS,
    SCL_CLASSES, VALID_SCL_CLASSES, INVALID_SCL_CLASSES,
    CLOUD_SHADOW_BUFFER_CLASSES, SCL_CLASS_GROUPS,
    L2A_SCALE_FACTOR, L2A_REFLECTANCE_OFFSET,
    PROCESSED_STRUCTURE, SAFE_EXTENSION,
    JP2_EXTENSION, GEOTIFF_EXTENSION,
    OVERWRITE_EXISTING, CREATE_VALID_MASK, CREATE_RGB_PREVIEW,
    APPLY_QUALITY_MASK_TO_BANDS, CLOUD_SHADOW_BUFFER_SIZE,
    REFLECTANCE_NORMALIZATION, SPATIAL_ALIGNMENT_CHECK
)

from .tiling_config import (
    TILES_DATA_DIR, DEFAULT_TILE_SIZE, MIN_VALID_PERCENTAGE,
    SKIP_INVALID_TILES, REFERENCE_YEAR
)

__all__ = [
    'BASE_DIR',
    'RAW_DATA_DIR',
    'PROCESSED_DATA_DIR',
    'TILES_DATA_DIR',
    'BAND_RESOLUTIONS',
    'RGB_BANDS',
    'QUALITY_BANDS',
    'SCL_CLASSES',
    'VALID_SCL_CLASSES',
    'INVALID_SCL_CLASSES',
    'CLOUD_SHADOW_BUFFER_CLASSES',
    'SCL_CLASS_GROUPS',
    'L2A_SCALE_FACTOR',
    'L2A_REFLECTANCE_OFFSET',
    'PROCESSED_STRUCTURE',
    'SAFE_EXTENSION',
    'JP2_EXTENSION',
    'GEOTIFF_EXTENSION',
    'OVERWRITE_EXISTING',
    'CREATE_VALID_MASK',
    'CREATE_RGB_PREVIEW',
    'APPLY_QUALITY_MASK_TO_BANDS',
    'CLOUD_SHADOW_BUFFER_SIZE',
    'REFLECTANCE_NORMALIZATION',
    'SPATIAL_ALIGNMENT_CHECK',
    'DEFAULT_TILE_SIZE',
    'MIN_VALID_PERCENTAGE',
    'SKIP_INVALID_TILES',
    'REFERENCE_YEAR'
]